---
baseurl: "https://kennyballou.com"
MetaDataFormat: "yaml"
languageCode: "en-us"
title: "~kballou"
indexes:
  tag: "tags"
  topic: "topics"
permalinks:
  blog: /blog/:year/:month/:slug
copyright: "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."
author:
  name: "Kenny Ballou"
...
